#                                                                        #
# Default subroutes configuration for the Blog package                   #
#                                                                        #

-
  name: 'Comment actions 1'
  uriPattern:    'posts/{post}/comments/{@action}'
  defaults:
    '@package':    'Blog'
    '@controller': 'Comment'
    '@format':     'html'
  routeParts:
    post:
      handler: F3\Blog\RoutePartHandlers\PostRoutePartHandler

-
  name: 'Posts Feed'
  uriPattern:    'feeds/posts.rss.xml'
  defaults:
    '@package':    'Blog'
    '@controller': 'Post'
    '@action':     'index'
    '@format':     'rss.xml'

-
  name: 'Single Post Actions'
  uriPattern:    'posts/{post}(/{@action})'
  defaults:
    '@package':    'Blog'
    '@controller': 'Post'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    post:
      handler: F3\Blog\RoutePartHandlers\PostRoutePartHandler

-
  name: 'General Posts Actions'
  uriPattern:    'posts(/{@action})'
  defaults:
    '@package':    'Blog'
    '@controller': 'Post'
    '@action':     'index'
    '@format':     'html'

-
  name: 'Single Category Actions'
  uriPattern:    'categories/{category}/{@action}'
  defaults:
    '@package':    'Blog'
    '@controller': 'Category'
    '@format':     'html'

-
  name: 'General Category Actions'
  uriPattern:    'categories(/{@action})'
  defaults:
    '@package':    'Blog'
    '@controller': 'Category'
    '@action':     'index'
    '@format':     'html'

-
  name: 'Account actions'
  uriPattern: 'admin/account(/{@action})'
  defaults:
    '@package':    'Blog'
    '@controller': 'Account'
    '@action':     'edit'
    '@format':     'html'

-
  name: 'Blog actions'
  uriPattern: 'admin/blog(/{@action})'
  defaults:
    '@package':    'Blog'
    '@controller': 'Blog'
    '@action':     'edit'
    '@format':     'html'

-
  name: 'Admin Overview'
  uriPattern: 'admin'
  defaults:
    '@package':    'Blog'
    '@controller': 'Admin'
    '@action':     'index'
    '@format':     'html'

-
  name: 'Setup'
  uriPattern: 'admin/setup(/{@action})'
  defaults:
    '@package':    'Blog'
    '@controller': 'Setup'
    '@action':     'index'

-
  name: 'Authentication Actions'
  uriPattern: 'admin/authentication(/{@action})'
  defaults:
    '@package':    'Blog'
    '@controller': 'Login'
    '@action':     'index'

-
  name: 'Fallback rule'
  uriPattern:    ''
  defaults:
    '@package':    'Blog'
    '@controller': 'Post'
    '@action':     'index'
    '@format':     'html'

