#                                                                        #
# Default subroutes configuration for the Blog package                   #
#                                                                        #

# $Id$


--
  name: 'Post'
  uriPattern:    'blogs/{blog}/{post}(.{@format})'
  defaults:
    @package:    Blog
    @controller: Post
    @action:     show
    @format:     html
  routeParts:
    blog:
      handler: F3\Blog\RoutePartHandlers\BlogRoutePartHandler
    post:
      handler: F3\Blog\RoutePartHandlers\PostRoutePartHandler

--
  name: 'Posts'
  uriPattern:    'blogs/{blog}/posts(.{@format})'
  defaults:
    @package:    Blog
    @controller: Post
    @action:     index
    @format:     html
  routeParts:
    blog:
      handler: F3\Blog\RoutePartHandlers\BlogRoutePartHandler

--
  name: 'Post actions 1'
  uriPattern:    'blogs/{blog}/posts/{post}/{@action}'
  defaults:
    @package:    Blog
    @controller: Post
    @format:     html
  routeParts:
    blog:
      handler: F3\Blog\RoutePartHandlers\BlogRoutePartHandler
    post:
      handler: F3\Blog\RoutePartHandlers\PostRoutePartHandler

--
  name: 'Post actions 2'
  uriPattern:    'blogs/{blog}/posts/{@action}'
  defaults:
    @package:    Blog
    @controller: Post
    @format:     html
  routeParts:
    blog:
      handler: F3\Blog\RoutePartHandlers\BlogRoutePartHandler

--
  name: 'Blog actions 1'
  uriPattern: 'blogs/{blog}/{@action}'
  defaults:
    @package:    Blog
    @controller: Blog
    @format:     html
  routeParts:
    blog:
      handler: F3\Blog\RoutePartHandlers\BlogRoutePartHandler

--
  name: 'Blog actions 2'
  uriPattern: 'blogs/{@action}'
  defaults:
    @package:    Blog
    @controller: Blog
    @format:     html

--
  name: 'Blogs'
  uriPattern: '(blogs)'
  defaults:
    @package:    Blog
    @controller: Blog
    @action:     index
    @format:     html

--
  name: 'Setup'
  uriPattern: 'setup'
  defaults:
    @package:    Blog
    @controller: Setup