#                                                                        #
# Default subroutes configuration for the Blog package                   #
#                                                                        #

# $Id$


-
  name: 'Comment actions 1'
  uriPattern:    'posts/{post}/comments/{@action}'
  defaults:
    '@package':    Blog
    '@controller': Comment
    '@format':     html
  routeParts:
    post:
      handler: F3\Blog\RoutePartHandlers\PostRoutePartHandler

-
  name: 'Posts Feed'
  uriPattern:    'feeds/posts.{@format}'
  defaults:
    '@package':    Blog
    '@controller': Post
    '@action':     index
    '@format':     html

-
  name: 'Post'
  uriPattern:    'posts/{post}.{@format}'
  defaults:
    '@package':    Blog
    '@controller': Post
    '@action':     show
    '@format':     html
  routeParts:
    post:
      handler: F3\Blog\RoutePartHandlers\PostRoutePartHandler

-
  name: 'Post actions 2'
  uriPattern:    'posts/{post}(/{@action})'
  defaults:
    '@package':    Blog
    '@controller': Post
    '@action':     show
    '@format':     html
  routeParts:
    post:
      handler: F3\Blog\RoutePartHandlers\PostRoutePartHandler

-
  name: 'Post actions 1'
  uriPattern:    'posts(/{@action})'
  defaults:
    '@package':    Blog
    '@controller': Post
    '@action':     index
    '@format':     html

-
  name: 'Post index'
  uriPattern:    '(posts)'
  defaults:
    '@package':    Blog
    '@controller': Post
    '@action':     index
    '@format':     html

-
  name: 'Post index with format'
  uriPattern:    'posts.{@format}'
  defaults:
    '@package':    Blog
    '@controller': Post
    '@action':     index
    '@format':     html

-
  name: 'Category actions 2'
  uriPattern:    'categories/{category}/{@action}'
  defaults:
    '@package':    Blog
    '@controller': Category
    '@format':     html

-
  name: 'Category actions 1'
  uriPattern:    'categories(/{@action})'
  defaults:
    '@package':    Blog
    '@controller': Category
    '@action':     index
    '@format':     html

-
  name: 'Category index'
  uriPattern:    '(categories)'
  defaults:
    '@package':    Blog
    '@controller': Category
    '@action':     index
    '@format':     html

-
  name: 'Account actions'
  uriPattern: 'admin/account(/{@action})'
  defaults:
    '@package':    Blog
    '@controller': Account
    '@action':     edit
    '@format':     html

-
  name: 'Blog actions 1'
  uriPattern: 'admin/blog(/{@action})'
  defaults:
    '@package':    Blog
    '@controller': Blog
    '@action':     edit
    '@format':     html

-
  name: 'Admin'
  uriPattern: 'admin'
  defaults:
    '@package':    Blog
    '@controller': Admin
    '@action':     index
    '@format':     html

-
  name: 'Setup'
  uriPattern: 'admin/setup(/{@action})'
  defaults:
    '@package':    Blog
    '@controller': Setup
    '@action':     index
    '@format':     html

-
  name: 'Authentication'
  uriPattern: 'admin/authentication(/{@action})'
  defaults:
    '@package':    Blog
    '@controller': Login
    '@action':     index
    '@format':     html
