#                                                                        #
# Settings Configuration for the Blog package                            #
#                                                                        #

# $Id$

