#                                                                        #
# Settings Configuration for the Blog package                            #
#                                                                        #

FLOW3:
  security:
    authentication:
      authenticationStrategy: oneToken
      providers:
        DefaultProvider:
          providerClass: PersistedUsernamePasswordProvider
          entryPoint:
            WebRedirect:
              uri: admin/authentication
