#                                                                        #
# Settings Configuration for the Blog package                            #
#                                                                        #

# $Id$

# How many entries to show for the "latest posts" view (maximum).
Blog:
  latestView:
    maxItems: 5
